ASPCORE e Entity Framework/Models/ErrorViewModel.cs
using System;

namespace ASPCORE.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASPCORE e Entity Framework/Models/Funcionario.cs
using System.Security.Cryptography.X509Certificates;
using System;

namespace ASPCORE.Models
{
    public class Funcionario
    {
        public int Id{get; set;}
        public string Nome{get;set;}
        public float Salario{get;set;}
        public string Cpf{get;set;}
    }
}

ASPCORE e Entity Framework/Controllers/FuncionariosController.cs
using ASPCORE.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using ASPCORE.Database;
using System.Linq;


namespace ASPCORE.Controllers
{
    public class FuncionariosController : Controller
    {

        private readonly ApplicationDBContext database;
        public FuncionariosController(ApplicationDBContext database){
            this.database = database;
        }

        public IActionResult Index(){
            var funcionarios = database.Funcionarios.ToList();
            return View(funcionarios);
        }
        public IActionResult Cadastrar(){
            return View();
        }

        public IActionResult Editar(int id){
            Funcionario funcionario = database.Funcionarios.First(registro => registro.Id == id);
            return View("Cadastrar", funcionario);
        }

        public IActionResult Deletar(int id){
            Funcionario funcionario = database.Funcionarios.First(registro => registro.Id == id);
            database.Funcionarios.Remove(funcionario);
            database.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Salvar(Funcionario funcionario){
            if(funcionario.Id == 0){
               database.Funcionarios.Add(funcionario);     
            }else{
               Funcionario funcionarioDoBanco = database.Funcionarios.First(registro => registro.Id == funcionario.Id);
               funcionarioDoBanco.Nome = funcionario.Nome;
               funcionarioDoBanco.Salario = funcionario.Salario;
               funcionarioDoBanco.Cpf = funcionario.Cpf;     
            }
            database.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ASPCORE e Entity Framework/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ASPCORE.Models;

namespace ASPCORE.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASPCORE e Entity Framework/Views/Funcionarios/Cadastrar.cshtml
@model ASPCORE.Models.Funcionario

<h2>Cadastro de Funcionarios</h2>

<form class="form-horizontal" asp-controller="Funcionarios" asp-action="Salvar" method="POST">
    <input type="hidden" asp-for="Id">
    <input type="text" class="form-control" asp-for="Nome" placeholder="Nome" > 
    <input type="number" class="form-control" asp-for="Salario"placeholder="Salario">
    <input type="text" class="form-control" asp-for="Cpf"placeholder="Cpf">
    <button class="btn btn-success">Cadastrar</button>
</form>

ASPCORE e Entity Framework/Views/Funcionarios/Index.cshtml
@model IEnumerable<ASPCORE.Models.Funcionario>

<h2>Todos os funcionarios</h2>
<a href="/Funcionarios/Cadastrar" class="btn btn-success">Novo Funcionario</a>
<hr>
@foreach (var funcionario in Model)
{
    <p>CPF:@funcionario.Cpf</p>
    <p>Nome:@funcionario.Nome</p>
    <p>Salario:@funcionario.Salario</p>
    <a href="/Funcionarios/Editar/@funcionario.Id" class="btn btn-success">Editar</a>
    <a href="/Funcionarios/Deletar/@funcionario.Id" class="btn btn-danger">Deletar</a>
    <hr>
}

ASPCORE e Entity Framework/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASPCORE e Entity Framework/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPCORE</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPCORE</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ASPCORE - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>